version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      angular: # group angular dependencies together
        patterns:
          - "@angular*"
      all: # group all minor/patch updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
